
stages:
  - build
  - deploy

build-docs:
  stage: build
  image: ubuntu:22.04
  script:
    - mkdir -p docs
    - apt update
    - apt install -y doxygen graphviz python3 python3-pip
    - pip3 install sphinx sphinx-rtd-theme breathe
    - doxygen
    - sphinx-build -b html . _build/html
  artifacts:
    paths:
      - _build/html
      - docs/html
    expire_in: 3 hours

deploy-docs:
  stage: deploy
  image: ubuntu:22.04
  dependencies:
    - build-docs
  pages: true
  script:
    - mkdir -p public/sphinx
    - mkdir -p public/doxygen
    - mv _build/html public/sphinx
    - mv docs/html public/doxygen
  artifacts:
    paths:
      - public/**

