
stages:
  - build
  - deploy

build-docs:
  stage: build
  image: ubuntu:22.04
  script:
    - mkdir -p docs
    - apt install -y doxygen graphviz
    - doxygen
  artifacts:
    paths:
      - docs/html
    expire_in: 3 hours

deploy-docs:
  stage: deploy
  image: ubuntu:22.04
  dependencies:
    - build-docs
  pages: true
  script:
    - mv docs/html public
  artifacts:
    paths:
      - public/**

