name: TinySLAM
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update packages
        run: sudo apt update

      - name: Install build tools
        run: sudo apt install -y build-essential cmake

      - name: Install dependencies
        run: sudo apt install -y libeigen3-dev

      - run: mkdir build && cd build
      - run: cmake ..
      - run: make -j8

